/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LatamButton {
        "customStyles"?: string;
        "href": string;
        "label": string;
    }
    interface LatamFaq {
        "answer": string;
        "question": string;
    }
    interface LatamProject {
        "category": string;
        "image": string;
        "name": string;
    }
    interface LatamService {
        "description": string;
        "image": string;
        "name": string;
    }
    interface LatamStrategyCard {
        "description": string;
        "name": string;
        "order": number;
    }
    interface LatamTeam {
        "area": string;
        "image": string;
        "name": string;
        "slogan": string;
    }
    interface LatamTestimonial {
        "area": string;
        "author": string;
        "image": string;
        "testimonial": string;
    }
}
declare global {
    interface HTMLLatamButtonElement extends Components.LatamButton, HTMLStencilElement {
    }
    var HTMLLatamButtonElement: {
        prototype: HTMLLatamButtonElement;
        new (): HTMLLatamButtonElement;
    };
    interface HTMLLatamFaqElement extends Components.LatamFaq, HTMLStencilElement {
    }
    var HTMLLatamFaqElement: {
        prototype: HTMLLatamFaqElement;
        new (): HTMLLatamFaqElement;
    };
    interface HTMLLatamProjectElement extends Components.LatamProject, HTMLStencilElement {
    }
    var HTMLLatamProjectElement: {
        prototype: HTMLLatamProjectElement;
        new (): HTMLLatamProjectElement;
    };
    interface HTMLLatamServiceElement extends Components.LatamService, HTMLStencilElement {
    }
    var HTMLLatamServiceElement: {
        prototype: HTMLLatamServiceElement;
        new (): HTMLLatamServiceElement;
    };
    interface HTMLLatamStrategyCardElement extends Components.LatamStrategyCard, HTMLStencilElement {
    }
    var HTMLLatamStrategyCardElement: {
        prototype: HTMLLatamStrategyCardElement;
        new (): HTMLLatamStrategyCardElement;
    };
    interface HTMLLatamTeamElement extends Components.LatamTeam, HTMLStencilElement {
    }
    var HTMLLatamTeamElement: {
        prototype: HTMLLatamTeamElement;
        new (): HTMLLatamTeamElement;
    };
    interface HTMLLatamTestimonialElement extends Components.LatamTestimonial, HTMLStencilElement {
    }
    var HTMLLatamTestimonialElement: {
        prototype: HTMLLatamTestimonialElement;
        new (): HTMLLatamTestimonialElement;
    };
    interface HTMLElementTagNameMap {
        "latam-button": HTMLLatamButtonElement;
        "latam-faq": HTMLLatamFaqElement;
        "latam-project": HTMLLatamProjectElement;
        "latam-service": HTMLLatamServiceElement;
        "latam-strategy-card": HTMLLatamStrategyCardElement;
        "latam-team": HTMLLatamTeamElement;
        "latam-testimonial": HTMLLatamTestimonialElement;
    }
}
declare namespace LocalJSX {
    interface LatamButton {
        "customStyles"?: string;
        "href"?: string;
        "label"?: string;
    }
    interface LatamFaq {
        "answer"?: string;
        "question"?: string;
    }
    interface LatamProject {
        "category"?: string;
        "image"?: string;
        "name"?: string;
    }
    interface LatamService {
        "description"?: string;
        "image"?: string;
        "name"?: string;
    }
    interface LatamStrategyCard {
        "description"?: string;
        "name"?: string;
        "order"?: number;
    }
    interface LatamTeam {
        "area"?: string;
        "image"?: string;
        "name"?: string;
        "slogan"?: string;
    }
    interface LatamTestimonial {
        "area"?: string;
        "author"?: string;
        "image"?: string;
        "testimonial"?: string;
    }
    interface IntrinsicElements {
        "latam-button": LatamButton;
        "latam-faq": LatamFaq;
        "latam-project": LatamProject;
        "latam-service": LatamService;
        "latam-strategy-card": LatamStrategyCard;
        "latam-team": LatamTeam;
        "latam-testimonial": LatamTestimonial;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "latam-button": LocalJSX.LatamButton & JSXBase.HTMLAttributes<HTMLLatamButtonElement>;
            "latam-faq": LocalJSX.LatamFaq & JSXBase.HTMLAttributes<HTMLLatamFaqElement>;
            "latam-project": LocalJSX.LatamProject & JSXBase.HTMLAttributes<HTMLLatamProjectElement>;
            "latam-service": LocalJSX.LatamService & JSXBase.HTMLAttributes<HTMLLatamServiceElement>;
            "latam-strategy-card": LocalJSX.LatamStrategyCard & JSXBase.HTMLAttributes<HTMLLatamStrategyCardElement>;
            "latam-team": LocalJSX.LatamTeam & JSXBase.HTMLAttributes<HTMLLatamTeamElement>;
            "latam-testimonial": LocalJSX.LatamTestimonial & JSXBase.HTMLAttributes<HTMLLatamTestimonialElement>;
        }
    }
}
